[package]
name = "solana_forward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.18.12"

[lib]
name = "solana_forward"
crate-type = ["cdylib", "lib"]
