name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: v1.18.21

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare cargo
      working-directory: childpda
      run: cargo add solana-program --package solana_forward
    - name: Build
      working-directory: childpda
      run: cargo build-bpf --manifest-path=./program/Cargo.toml --bpf-out-dir=./program/target/so --verbose
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn run tests
      
