name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.18.21

jobs:
  build:

    runs-on: ubuntu-latest
#    container: projectserum/build:v0.24.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Solana
      id: cache-solana
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/solana/install/releases/${{ env.SOLANA_VERSION }}
          ~/.cache/solana
        key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}

    - name: Install solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      run: sh -c "$(curl -sSfL https://release.solana.com/v$SOLANA_VERSION/install)"

    - name: Check Solana 1
      run: |
        ls -l ~/.local/share/solana/install/ 

    - name: Check Solana 2
      run: |
        ls -l ~/.local/share/solana/install/releases/$SOLANA_VERSION

    - name: Check Solana 3
      run: |
        ls -l "~/.local/share/solana/install/releases/$SOLANA_VERSION/solana-release"

#    - name: Check Solana 4
#      run: |
#        ls -l ~/.local/share/solana/install/active_release/bin

    - name: Set Active Solana Version
      run: |
        ls -l "~/.local/share/solana/install/releases/$SOLANA_VERSION/solana-release"
        rm -f "~/.local/share/solana/install/active_release"
        ln -s "~/.local/share/solana/install/releases/$SOLANA_VERSION/solana-release" "~/.local/share/solana/install/active_release"
      shell: bash


    - name: Configure Solana
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH



#    - name: Set up cargo cache
#      uses: actions/cache@v4
#      with:
#        path: |
#          ~/.cargo/bin/
#          ~/.cargo/registry/index/
#          ~/.cargo/registry/cache/
#          ~/.cargo/git/db/
#          target/
#        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

#    - name: Checkout Solana
#      uses: actions/checkout@v4
#      with:
#        repository: solana-labs/solana
#        ref: 'v1.18.21'
#        path: 'solana'
#
#    - name: Add Solana to Path
#      run: echo "`pwd`/solana" >> $GITHUB_PATH
#    - name: Build
#      working-directory: childpda
#      run: cargo build-sbf --manifest-path=./program/Cargo.toml --sbf-out-dir=./program/target/so
#    - name: Use Node.js
#      uses: actions/setup-node@v4
#      with:
#        node-version: '20.x'
#    - name: Install dependencies
#      run: yarn --frozen-lockfile
#      working-directory: childpda
#    - name: Run tests
#      run: yarn run tests
#      working-directory: childpda
      
